export const PaywallTexts = {
  title: "PlantApp Premium",
  subtitle: "Access All Features",
  feature1: "Unlimited Plant Identify",
  feature2: "Faster Process",
  feature3: "Detailed Plant Data",
  feature4: "Priority Support",
  monthlyPlan: "1 Month",
  monthlyPrice: "$2.99/month",
  yearlyPlan: "1 Year",
  yearlyPrice: "$29.99/year",
  saveBadge: "Save 50%",
  ctaButton: "Try free for 3 days",
  subscriptionInfo: "After the 3-day free trial period you'll be charged $29.99 per year unless you cancel before the trial expires. Subscription is auto-renewable. Cancel anytime.",
  termsLink: "Terms of Use",
  privacyLink: "Privacy Policy",
  restoreLink: "Restore Purchase",
  closeButton: "✕",
}; 